import { createFileRoute } from '@tanstack/react-router'
import { useState, useEffect } from 'react'
import { AdminLayout } from '@/components/AdminLayout'
import { supabase } from '@/integrations/supabase/client'
import { CheckCircle2, MousePointerClick } from 'lucide-react'

export const Route = createFileRoute('/admin/sales')({
  component: SalesDashboard,
})

interface SalesLead {
  id: string;
  company: string;
  email: string;
  industry: string;
  website: string;
  logo_url: string;
  mockup_url: string;
  created_at: string;
  clicked: boolean;
  clicked_at: string | null;
}

function SalesDashboard() {
  const [leads, setLeads] = useState<SalesLead[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    supabase
      .from('sales_leads')
      .select('*')
      .order('created_at', { ascending: false })
      .then(({ data, error }) => {
        if (error) {
          console.error("Failed to fetch sales leads from Supabase", error);
        } else {
          setLeads(data as SalesLead[]);
        }
      })
      .finally(() => setLoading(false));
  }, []);

  return (
    <AdminLayout>
      <div className="px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto">
        <div className="mb-8 flex justify-between items-end">
          <div>
            <h1 className="text-3xl font-bold text-gray-900 tracking-tight">AI Sales Dashboard</h1>
            <p className="mt-2 text-sm text-gray-500">Track all automated cold email outreach generated by the AI Prospector.</p>
          </div>
          <div className="text-right">
            <span className="text-2xl font-bold text-primary">{leads.length}</span>
            <p className="text-sm text-gray-500 uppercase font-semibold tracking-wider">Total Leads Contacted</p>
          </div>
        </div>

        {loading ? (
          <div className="animate-pulse space-y-4">
            {[...Array(5)].map((_, i) => (
              <div key={i} className="h-24 bg-white rounded-xl shadow-sm"></div>
            ))}
          </div>
        ) : leads.length === 0 ? (
          <div className="text-center py-20 bg-white rounded-xl shadow-sm border border-gray-100">
            <h3 className="text-lg font-medium text-gray-900">No leads contacted yet</h3>
            <p className="mt-1 text-gray-500">The daily script hasn't successfully processed any leads yet.</p>
          </div>
        ) : (
          <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th scope="col" className="px-6 py-4 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Company
                    </th>
                    <th scope="col" className="px-6 py-4 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Contact Info
                    </th>
                    <th scope="col" className="px-6 py-4 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Date Contacted
                    </th>
                    <th scope="col" className="px-6 py-4 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Status
                    </th>
                    <th scope="col" className="px-6 py-4 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Mockup Preview
                    </th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  {leads.map((lead, idx) => (
                    <tr key={idx} className="hover:bg-gray-50 transition-colors">
                      <td className="px-6 py-6 whitespace-nowrap">
                        <div className="flex items-center">
                          <div className="flex-shrink-0 h-10 w-10 bg-gray-100 rounded-full flex items-center justify-center p-1 overflow-hidden border border-gray-200">
                            <img className="max-h-full max-w-full object-contain" src={lead.logo_url} alt="" />
                          </div>
                          <div className="ml-4">
                            <div className="text-sm font-bold text-gray-900">{lead.company}</div>
                            <div className="text-xs text-gray-500 mt-1">{lead.industry}</div>
                          </div>
                        </div>
                      </td>
                      <td className="px-6 py-6 whitespace-nowrap">
                        <div className="text-sm text-gray-900">{lead.email}</div>
                        <a href={lead.website} target="_blank" rel="noreferrer" className="text-xs text-primary hover:underline mt-1 inline-block">
                          Visit Website &rarr;
                        </a>
                      </td>
                      <td className="px-6 py-6 whitespace-nowrap">
                        <div className="text-sm text-gray-900">
                          {new Date(lead.created_at).toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' })}
                        </div>
                        <div className="text-xs text-gray-500 mt-1">
                          {new Date(lead.created_at).toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit' })}
                        </div>
                      </td>
                      <td className="px-6 py-6 whitespace-nowrap text-center">
                        {lead.clicked ? (
                          <div className="inline-flex items-center space-x-1.5 px-3 py-1 rounded-full bg-green-50 text-green-700 border border-green-200">
                            <MousePointerClick className="w-4 h-4" />
                            <span className="text-xs font-bold tracking-wide">CLICKED</span>
                          </div>
                        ) : (
                          <div className="inline-flex items-center space-x-1.5 px-3 py-1 rounded-full bg-gray-50 text-gray-500 border border-gray-200">
                            <CheckCircle2 className="w-4 h-4" />
                            <span className="text-xs font-medium tracking-wide">Sent</span>
                          </div>
                        )}
                      </td>
                      <td className="px-6 py-6 whitespace-nowrap text-center">
                        {lead.mockup_url ? (
                          <a href={lead.mockup_url} target="_blank" rel="noreferrer" className="inline-block relative group">
                            <img src={lead.mockup_url} alt="Mockup" className="h-20 w-auto rounded border border-gray-200 shadow-sm transition-transform transform group-hover:scale-105" />
                            <div className="absolute inset-0 bg-black bg-opacity-0 group-hover:bg-opacity-10 transition-all rounded flex items-center justify-center">
                               <span className="opacity-0 group-hover:opacity-100 text-xs font-bold bg-white px-2 py-1 rounded shadow-sm text-gray-900">View</span>
                            </div>
                          </a>
                        ) : (
                          <span className="text-xs text-gray-400 italic">No mockup generated</span>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </div>
    </AdminLayout>
  );
}
