/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShirtColorsRouteImport } from './routes/shirt-colors'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImagePlacementsRouteImport } from './routes/image-placements'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ArtworkGuidelinesRouteImport } from './routes/artwork-guidelines'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ServicesTeamBulkRouteImport } from './routes/services.team-bulk'
import { Route as ServicesPromotionalProductsRouteImport } from './routes/services.promotional-products'
import { Route as ServicesFamilyTeesRouteImport } from './routes/services.family-tees'
import { Route as ServicesDtfTransfersRouteImport } from './routes/services.dtf-transfers'
import { Route as ServicesCustomTshirtsRouteImport } from './routes/services.custom-tshirts'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as MockupIdRouteImport } from './routes/mockup.$id'
import { Route as LocationsSlugRouteImport } from './routes/locations.$slug'
import { Route as LandingCustomShirtsRouteImport } from './routes/landing.custom-shirts'
import { Route as LandingBundleDealRouteImport } from './routes/landing.bundle-deal'
import { Route as LandingBulkPrintingRouteImport } from './routes/landing.bulk-printing'
import { Route as GroupNewHeightsYouthAdminRouteImport } from './routes/group.new-heights-youth-admin'
import { Route as GroupNewHeightsYouthRouteImport } from './routes/group.new-heights-youth'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiGroupAdminRouteImport } from './routes/api.group-admin'
import { Route as AdminSubscribersRouteImport } from './routes/admin.subscribers'
import { Route as AdminSalesRouteImport } from './routes/admin.sales'
import { Route as AdminQuotesRouteImport } from './routes/admin.quotes'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminEtsyRouteImport } from './routes/admin.etsy'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminAnnouncementRouteImport } from './routes/admin.announcement'
import { Route as ApiPublicVoiceRouteImport } from './routes/api/public/voice'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as ApiCronGenerateBlogRouteImport } from './routes/api/cron/generate-blog'
import { Route as ApiPublicHooksGenerateBlogPostRouteImport } from './routes/api/public/hooks/generate-blog-post'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShirtColorsRoute = ShirtColorsRouteImport.update({
  id: '/shirt-colors',
  path: '/shirt-colors',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagePlacementsRoute = ImagePlacementsRouteImport.update({
  id: '/image-placements',
  path: '/image-placements',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtworkGuidelinesRoute = ArtworkGuidelinesRouteImport.update({
  id: '/artwork-guidelines',
  path: '/artwork-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTeamBulkRoute = ServicesTeamBulkRouteImport.update({
  id: '/services/team-bulk',
  path: '/services/team-bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPromotionalProductsRoute =
  ServicesPromotionalProductsRouteImport.update({
    id: '/services/promotional-products',
    path: '/services/promotional-products',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesFamilyTeesRoute = ServicesFamilyTeesRouteImport.update({
  id: '/services/family-tees',
  path: '/services/family-tees',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDtfTransfersRoute = ServicesDtfTransfersRouteImport.update({
  id: '/services/dtf-transfers',
  path: '/services/dtf-transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCustomTshirtsRoute = ServicesCustomTshirtsRouteImport.update({
  id: '/services/custom-tshirts',
  path: '/services/custom-tshirts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupIdRoute = MockupIdRouteImport.update({
  id: '/mockup/$id',
  path: '/mockup/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/locations/$slug',
  path: '/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingCustomShirtsRoute = LandingCustomShirtsRouteImport.update({
  id: '/landing/custom-shirts',
  path: '/landing/custom-shirts',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingBundleDealRoute = LandingBundleDealRouteImport.update({
  id: '/landing/bundle-deal',
  path: '/landing/bundle-deal',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingBulkPrintingRoute = LandingBulkPrintingRouteImport.update({
  id: '/landing/bulk-printing',
  path: '/landing/bulk-printing',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupNewHeightsYouthAdminRoute =
  GroupNewHeightsYouthAdminRouteImport.update({
    id: '/group/new-heights-youth-admin',
    path: '/group/new-heights-youth-admin',
    getParentRoute: () => rootRouteImport,
  } as any)
const GroupNewHeightsYouthRoute = GroupNewHeightsYouthRouteImport.update({
  id: '/group/new-heights-youth',
  path: '/group/new-heights-youth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGroupAdminRoute = ApiGroupAdminRouteImport.update({
  id: '/api/group-admin',
  path: '/api/group-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/admin/subscribers',
  path: '/admin/subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/admin/sales',
  path: '/admin/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/admin/quotes',
  path: '/admin/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/admin/projects',
  path: '/admin/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEtsyRoute = AdminEtsyRouteImport.update({
  id: '/admin/etsy',
  path: '/admin/etsy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementRoute = AdminAnnouncementRouteImport.update({
  id: '/admin/announcement',
  path: '/admin/announcement',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVoiceRoute = ApiPublicVoiceRouteImport.update({
  id: '/api/public/voice',
  path: '/api/public/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronGenerateBlogRoute = ApiCronGenerateBlogRouteImport.update({
  id: '/api/cron/generate-blog',
  path: '/api/cron/generate-blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksGenerateBlogPostRoute =
  ApiPublicHooksGenerateBlogPostRouteImport.update({
    id: '/api/public/hooks/generate-blog-post',
    path: '/api/public/hooks/generate-blog-post',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/artwork-guidelines': typeof ArtworkGuidelinesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/image-placements': typeof ImagePlacementsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/returns': typeof ReturnsRoute
  '/reviews': typeof ReviewsRoute
  '/shirt-colors': typeof ShirtColorsRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/admin/announcement': typeof AdminAnnouncementRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/etsy': typeof AdminEtsyRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/api/group-admin': typeof ApiGroupAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/group/new-heights-youth': typeof GroupNewHeightsYouthRoute
  '/group/new-heights-youth-admin': typeof GroupNewHeightsYouthAdminRoute
  '/landing/bulk-printing': typeof LandingBulkPrintingRoute
  '/landing/bundle-deal': typeof LandingBundleDealRoute
  '/landing/custom-shirts': typeof LandingCustomShirtsRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/mockup/$id': typeof MockupIdRoute
  '/product/$handle': typeof ProductHandleRoute
  '/services/custom-tshirts': typeof ServicesCustomTshirtsRoute
  '/services/dtf-transfers': typeof ServicesDtfTransfersRoute
  '/services/family-tees': typeof ServicesFamilyTeesRoute
  '/services/promotional-products': typeof ServicesPromotionalProductsRoute
  '/services/team-bulk': typeof ServicesTeamBulkRoute
  '/blog/': typeof BlogIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/api/cron/generate-blog': typeof ApiCronGenerateBlogRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/api/public/voice': typeof ApiPublicVoiceRoute
  '/api/public/hooks/generate-blog-post': typeof ApiPublicHooksGenerateBlogPostRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/artwork-guidelines': typeof ArtworkGuidelinesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/image-placements': typeof ImagePlacementsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/returns': typeof ReturnsRoute
  '/reviews': typeof ReviewsRoute
  '/shirt-colors': typeof ShirtColorsRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/admin/announcement': typeof AdminAnnouncementRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/etsy': typeof AdminEtsyRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/api/group-admin': typeof ApiGroupAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/group/new-heights-youth': typeof GroupNewHeightsYouthRoute
  '/group/new-heights-youth-admin': typeof GroupNewHeightsYouthAdminRoute
  '/landing/bulk-printing': typeof LandingBulkPrintingRoute
  '/landing/bundle-deal': typeof LandingBundleDealRoute
  '/landing/custom-shirts': typeof LandingCustomShirtsRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/mockup/$id': typeof MockupIdRoute
  '/product/$handle': typeof ProductHandleRoute
  '/services/custom-tshirts': typeof ServicesCustomTshirtsRoute
  '/services/dtf-transfers': typeof ServicesDtfTransfersRoute
  '/services/family-tees': typeof ServicesFamilyTeesRoute
  '/services/promotional-products': typeof ServicesPromotionalProductsRoute
  '/services/team-bulk': typeof ServicesTeamBulkRoute
  '/blog': typeof BlogIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/api/cron/generate-blog': typeof ApiCronGenerateBlogRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/api/public/voice': typeof ApiPublicVoiceRoute
  '/api/public/hooks/generate-blog-post': typeof ApiPublicHooksGenerateBlogPostRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/artwork-guidelines': typeof ArtworkGuidelinesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/image-placements': typeof ImagePlacementsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/returns': typeof ReturnsRoute
  '/reviews': typeof ReviewsRoute
  '/shirt-colors': typeof ShirtColorsRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/admin/announcement': typeof AdminAnnouncementRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/etsy': typeof AdminEtsyRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/api/group-admin': typeof ApiGroupAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/group/new-heights-youth': typeof GroupNewHeightsYouthRoute
  '/group/new-heights-youth-admin': typeof GroupNewHeightsYouthAdminRoute
  '/landing/bulk-printing': typeof LandingBulkPrintingRoute
  '/landing/bundle-deal': typeof LandingBundleDealRoute
  '/landing/custom-shirts': typeof LandingCustomShirtsRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/mockup/$id': typeof MockupIdRoute
  '/product/$handle': typeof ProductHandleRoute
  '/services/custom-tshirts': typeof ServicesCustomTshirtsRoute
  '/services/dtf-transfers': typeof ServicesDtfTransfersRoute
  '/services/family-tees': typeof ServicesFamilyTeesRoute
  '/services/promotional-products': typeof ServicesPromotionalProductsRoute
  '/services/team-bulk': typeof ServicesTeamBulkRoute
  '/blog/': typeof BlogIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/api/cron/generate-blog': typeof ApiCronGenerateBlogRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/api/public/voice': typeof ApiPublicVoiceRoute
  '/api/public/hooks/generate-blog-post': typeof ApiPublicHooksGenerateBlogPostRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/artwork-guidelines'
    | '/contact'
    | '/faq'
    | '/image-placements'
    | '/login'
    | '/privacy'
    | '/quote'
    | '/returns'
    | '/reviews'
    | '/shirt-colors'
    | '/shop'
    | '/terms'
    | '/track'
    | '/admin/announcement'
    | '/admin/blog'
    | '/admin/etsy'
    | '/admin/projects'
    | '/admin/quotes'
    | '/admin/sales'
    | '/admin/subscribers'
    | '/api/group-admin'
    | '/blog/$slug'
    | '/group/new-heights-youth'
    | '/group/new-heights-youth-admin'
    | '/landing/bulk-printing'
    | '/landing/bundle-deal'
    | '/landing/custom-shirts'
    | '/locations/$slug'
    | '/mockup/$id'
    | '/product/$handle'
    | '/services/custom-tshirts'
    | '/services/dtf-transfers'
    | '/services/family-tees'
    | '/services/promotional-products'
    | '/services/team-bulk'
    | '/blog/'
    | '/locations/'
    | '/api/cron/generate-blog'
    | '/api/public/track'
    | '/api/public/voice'
    | '/api/public/hooks/generate-blog-post'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/artwork-guidelines'
    | '/contact'
    | '/faq'
    | '/image-placements'
    | '/login'
    | '/privacy'
    | '/quote'
    | '/returns'
    | '/reviews'
    | '/shirt-colors'
    | '/shop'
    | '/terms'
    | '/track'
    | '/admin/announcement'
    | '/admin/blog'
    | '/admin/etsy'
    | '/admin/projects'
    | '/admin/quotes'
    | '/admin/sales'
    | '/admin/subscribers'
    | '/api/group-admin'
    | '/blog/$slug'
    | '/group/new-heights-youth'
    | '/group/new-heights-youth-admin'
    | '/landing/bulk-printing'
    | '/landing/bundle-deal'
    | '/landing/custom-shirts'
    | '/locations/$slug'
    | '/mockup/$id'
    | '/product/$handle'
    | '/services/custom-tshirts'
    | '/services/dtf-transfers'
    | '/services/family-tees'
    | '/services/promotional-products'
    | '/services/team-bulk'
    | '/blog'
    | '/locations'
    | '/api/cron/generate-blog'
    | '/api/public/track'
    | '/api/public/voice'
    | '/api/public/hooks/generate-blog-post'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/artwork-guidelines'
    | '/contact'
    | '/faq'
    | '/image-placements'
    | '/login'
    | '/privacy'
    | '/quote'
    | '/returns'
    | '/reviews'
    | '/shirt-colors'
    | '/shop'
    | '/terms'
    | '/track'
    | '/admin/announcement'
    | '/admin/blog'
    | '/admin/etsy'
    | '/admin/projects'
    | '/admin/quotes'
    | '/admin/sales'
    | '/admin/subscribers'
    | '/api/group-admin'
    | '/blog/$slug'
    | '/group/new-heights-youth'
    | '/group/new-heights-youth-admin'
    | '/landing/bulk-printing'
    | '/landing/bundle-deal'
    | '/landing/custom-shirts'
    | '/locations/$slug'
    | '/mockup/$id'
    | '/product/$handle'
    | '/services/custom-tshirts'
    | '/services/dtf-transfers'
    | '/services/family-tees'
    | '/services/promotional-products'
    | '/services/team-bulk'
    | '/blog/'
    | '/locations/'
    | '/api/cron/generate-blog'
    | '/api/public/track'
    | '/api/public/voice'
    | '/api/public/hooks/generate-blog-post'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArtworkGuidelinesRoute: typeof ArtworkGuidelinesRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ImagePlacementsRoute: typeof ImagePlacementsRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  QuoteRoute: typeof QuoteRoute
  ReturnsRoute: typeof ReturnsRoute
  ReviewsRoute: typeof ReviewsRoute
  ShirtColorsRoute: typeof ShirtColorsRoute
  ShopRoute: typeof ShopRoute
  TermsRoute: typeof TermsRoute
  TrackRoute: typeof TrackRoute
  AdminAnnouncementRoute: typeof AdminAnnouncementRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminEtsyRoute: typeof AdminEtsyRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminQuotesRoute: typeof AdminQuotesRoute
  AdminSalesRoute: typeof AdminSalesRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  ApiGroupAdminRoute: typeof ApiGroupAdminRoute
  BlogSlugRoute: typeof BlogSlugRoute
  GroupNewHeightsYouthRoute: typeof GroupNewHeightsYouthRoute
  GroupNewHeightsYouthAdminRoute: typeof GroupNewHeightsYouthAdminRoute
  LandingBulkPrintingRoute: typeof LandingBulkPrintingRoute
  LandingBundleDealRoute: typeof LandingBundleDealRoute
  LandingCustomShirtsRoute: typeof LandingCustomShirtsRoute
  LocationsSlugRoute: typeof LocationsSlugRoute
  MockupIdRoute: typeof MockupIdRoute
  ProductHandleRoute: typeof ProductHandleRoute
  ServicesCustomTshirtsRoute: typeof ServicesCustomTshirtsRoute
  ServicesDtfTransfersRoute: typeof ServicesDtfTransfersRoute
  ServicesFamilyTeesRoute: typeof ServicesFamilyTeesRoute
  ServicesPromotionalProductsRoute: typeof ServicesPromotionalProductsRoute
  ServicesTeamBulkRoute: typeof ServicesTeamBulkRoute
  BlogIndexRoute: typeof BlogIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  ApiCronGenerateBlogRoute: typeof ApiCronGenerateBlogRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
  ApiPublicVoiceRoute: typeof ApiPublicVoiceRoute
  ApiPublicHooksGenerateBlogPostRoute: typeof ApiPublicHooksGenerateBlogPostRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shirt-colors': {
      id: '/shirt-colors'
      path: '/shirt-colors'
      fullPath: '/shirt-colors'
      preLoaderRoute: typeof ShirtColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-placements': {
      id: '/image-placements'
      path: '/image-placements'
      fullPath: '/image-placements'
      preLoaderRoute: typeof ImagePlacementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artwork-guidelines': {
      id: '/artwork-guidelines'
      path: '/artwork-guidelines'
      fullPath: '/artwork-guidelines'
      preLoaderRoute: typeof ArtworkGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/team-bulk': {
      id: '/services/team-bulk'
      path: '/services/team-bulk'
      fullPath: '/services/team-bulk'
      preLoaderRoute: typeof ServicesTeamBulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/promotional-products': {
      id: '/services/promotional-products'
      path: '/services/promotional-products'
      fullPath: '/services/promotional-products'
      preLoaderRoute: typeof ServicesPromotionalProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/family-tees': {
      id: '/services/family-tees'
      path: '/services/family-tees'
      fullPath: '/services/family-tees'
      preLoaderRoute: typeof ServicesFamilyTeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/dtf-transfers': {
      id: '/services/dtf-transfers'
      path: '/services/dtf-transfers'
      fullPath: '/services/dtf-transfers'
      preLoaderRoute: typeof ServicesDtfTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/custom-tshirts': {
      id: '/services/custom-tshirts'
      path: '/services/custom-tshirts'
      fullPath: '/services/custom-tshirts'
      preLoaderRoute: typeof ServicesCustomTshirtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockup/$id': {
      id: '/mockup/$id'
      path: '/mockup/$id'
      fullPath: '/mockup/$id'
      preLoaderRoute: typeof MockupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/locations/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/custom-shirts': {
      id: '/landing/custom-shirts'
      path: '/landing/custom-shirts'
      fullPath: '/landing/custom-shirts'
      preLoaderRoute: typeof LandingCustomShirtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/bundle-deal': {
      id: '/landing/bundle-deal'
      path: '/landing/bundle-deal'
      fullPath: '/landing/bundle-deal'
      preLoaderRoute: typeof LandingBundleDealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/bulk-printing': {
      id: '/landing/bulk-printing'
      path: '/landing/bulk-printing'
      fullPath: '/landing/bulk-printing'
      preLoaderRoute: typeof LandingBulkPrintingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/new-heights-youth-admin': {
      id: '/group/new-heights-youth-admin'
      path: '/group/new-heights-youth-admin'
      fullPath: '/group/new-heights-youth-admin'
      preLoaderRoute: typeof GroupNewHeightsYouthAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/new-heights-youth': {
      id: '/group/new-heights-youth'
      path: '/group/new-heights-youth'
      fullPath: '/group/new-heights-youth'
      preLoaderRoute: typeof GroupNewHeightsYouthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/group-admin': {
      id: '/api/group-admin'
      path: '/api/group-admin'
      fullPath: '/api/group-admin'
      preLoaderRoute: typeof ApiGroupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/admin/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/admin/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/admin/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/etsy': {
      id: '/admin/etsy'
      path: '/admin/etsy'
      fullPath: '/admin/etsy'
      preLoaderRoute: typeof AdminEtsyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcement': {
      id: '/admin/announcement'
      path: '/admin/announcement'
      fullPath: '/admin/announcement'
      preLoaderRoute: typeof AdminAnnouncementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/voice': {
      id: '/api/public/voice'
      path: '/api/public/voice'
      fullPath: '/api/public/voice'
      preLoaderRoute: typeof ApiPublicVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/generate-blog': {
      id: '/api/cron/generate-blog'
      path: '/api/cron/generate-blog'
      fullPath: '/api/cron/generate-blog'
      preLoaderRoute: typeof ApiCronGenerateBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-blog-post': {
      id: '/api/public/hooks/generate-blog-post'
      path: '/api/public/hooks/generate-blog-post'
      fullPath: '/api/public/hooks/generate-blog-post'
      preLoaderRoute: typeof ApiPublicHooksGenerateBlogPostRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArtworkGuidelinesRoute: ArtworkGuidelinesRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ImagePlacementsRoute: ImagePlacementsRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  QuoteRoute: QuoteRoute,
  ReturnsRoute: ReturnsRoute,
  ReviewsRoute: ReviewsRoute,
  ShirtColorsRoute: ShirtColorsRoute,
  ShopRoute: ShopRoute,
  TermsRoute: TermsRoute,
  TrackRoute: TrackRoute,
  AdminAnnouncementRoute: AdminAnnouncementRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminEtsyRoute: AdminEtsyRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminQuotesRoute: AdminQuotesRoute,
  AdminSalesRoute: AdminSalesRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  ApiGroupAdminRoute: ApiGroupAdminRoute,
  BlogSlugRoute: BlogSlugRoute,
  GroupNewHeightsYouthRoute: GroupNewHeightsYouthRoute,
  GroupNewHeightsYouthAdminRoute: GroupNewHeightsYouthAdminRoute,
  LandingBulkPrintingRoute: LandingBulkPrintingRoute,
  LandingBundleDealRoute: LandingBundleDealRoute,
  LandingCustomShirtsRoute: LandingCustomShirtsRoute,
  LocationsSlugRoute: LocationsSlugRoute,
  MockupIdRoute: MockupIdRoute,
  ProductHandleRoute: ProductHandleRoute,
  ServicesCustomTshirtsRoute: ServicesCustomTshirtsRoute,
  ServicesDtfTransfersRoute: ServicesDtfTransfersRoute,
  ServicesFamilyTeesRoute: ServicesFamilyTeesRoute,
  ServicesPromotionalProductsRoute: ServicesPromotionalProductsRoute,
  ServicesTeamBulkRoute: ServicesTeamBulkRoute,
  BlogIndexRoute: BlogIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  ApiCronGenerateBlogRoute: ApiCronGenerateBlogRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
  ApiPublicVoiceRoute: ApiPublicVoiceRoute,
  ApiPublicHooksGenerateBlogPostRoute: ApiPublicHooksGenerateBlogPostRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
